
export const types = {
  RESIZE_WINDOW: "RESIZE_WINDOW",
  CHANGE_TAB: "CHANGE_TAB",
  TAB1_INIT: "TAB1_INIT",
  SHOW_SETTING: "SHOW_SETTING",
  CLOSE_SETTING: "CLOSE_SETTING",
  SHOW_PROFILE: "SHOW_PROFILE",
  SHOW_NESTED_PROFILE: "SHOW_NESTED_PROFILE",
  CHANGE_PROFILE: "CHANGE_PROFILE",
  CLOSE_PROFILE: "CLOSE_PROFILE",
  PREDICT: "PREDICT",
  PREDICTED: "PREDICTED",
  OPTIMIZE: "OPTIMIZE",
  OPTIMIZED: "OPTIMIZED",
  LOAD_STAFFS: "LOAD_STAFFS",
  LOADED_STAFFS: "LOADED_STAFFS",
  UPDATE_DAY_OFFS: "UPDATE_DAY_OFFS",
}
